### ISSUE TITLE
Result symlinks override each other

### ISSUE THREAD

**Issue by andir** [Mic92/nix-fast-build#25]
When building an attributeset of derivations the result links are not stored individually. One randomly wins over the others. it would be good to either number them (`result-1`, `result-2`, ..) or have them follow the attribute names that are being built (`result-a`, `result-foo`, ..).

**Comment by Mic92** [comment]
Fixed in https://github.com/Mic92/nix-fast-build/commit/77c764981a9738aadb55b80e3e0891e6f2572477
