### ISSUE TITLE
Why not use the system Nix?

### ISSUE THREAD

**Issue by lovesegfault** [Mic92/nix-fast-build#26]
I'm just curious why the derivation picks up Nix from `nixpkgs` here:
https://github.com/Mic92/nix-fast-build/blob/9ebfd443483595bea4644e421ce334706088a7d4/default.nix#L3

As opposed to just relying on the `nix` from `$PATH`.

It means that every time you want to run `nix-fast-build`, even if you already have Nix installed, you always need to fetch the entire `nix` closure from cache, or build it if it was overlayed/uncached.

Is there a strong dependency on the specific version of Nix the tool uses? I was thinking of overriding the build on my end to remove that bit.

**Comment by lovesegfault** [comment]
I'm reopening this because I am now wondering whether `nix-eval-jobs` should expose its version of `nix` through `passthrough`, and then `nix-fast-build` could use that specifically instead of just `nix` here: https://github.com/Mic92/nix-fast-build/blob/9ebfd443483595bea4644e421ce334706088a7d4/default.nix#L3

**Comment by Mic92** [comment]
I first would need a nix passthru in nix-eval-jobs for the nix package manager.

**Comment by lovesegfault** [comment]
PR opened to `nixpkgs`: https://github.com/NixOS/nixpkgs/pull/259411

**Comment by Mic92** [comment]
Ok. waiting for: https://nixpk.gs/pr-tracker.html?pr=259411

**Comment by Mic92** [comment]
addressed in https://github.com/Mic92/nix-fast-build/pull/38
