### ISSUE TITLE
Don't evaluate other systems (option?)

### ISSUE THREAD

**Issue by dpc** [Mic92/nix-fast-build#29]
After I "fixed" my flake to make sure there are no evaluations that wouldn't be possible to build on supported system I still get:

```
> nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --systems "x86_64-linux"

              (stack trace truncated; use '--show-trace' to show the full trace)

              error: a 'x86_64-darwin' with features {} is required to build '/nix/store/09par5vs5qdw9ylw0ckf6wg3xi94gdg1-android-googletv-license.drv', but I am a 'x86_64-linux' with features {be
nchmark, big-parallel, kvm, nixos-test}
```

which suggest, that even on `x86_64-linux`, there are some reachable things somewhere that actually don't compile on it? Possibly they are coming from `nixpkgs-android` which is an intput I don't control.

I don't really hit these issues with `nix flake check` or `nix build`, and it's unclear to me is some problem of my flake,`nixpkgs-android` or how `nix-fast-build` does things.

One way or another, I'd rather disable evaluation of other systems and move on.

**Comment by lovesegfault** [comment]
I'm guessing this is due to IFD somewhere?

**Comment by Mic92** [comment]
This will stop evaluating other architectures:

```
$ nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#checks.x86_64-linux"
```

**Comment by dpc** [comment]
> This will stop evaluating other architectures:

What's the best system-agnostic version?

**Comment by Mic92** [comment]
You can do this:

```
$ nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem')"
```
