### ISSUE TITLE
currently hides eval failures

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-fast-build#31]
I have a CI job setup to auto-update-rebase my nixpkgs/home-manager forks, update my other flake inputs, and build. I haven't received any job failures recently.

Turns out, I had `nixos-hardware` set to an old fork and got bit by the rocm packages change. However, my CI jobs are all still green.

It seems that nix-fast-build did spit out an error, but must have exitted 0 at the end, since the script kept going and GHA didn't complain.

Is it possible to change this behavior, either by default or with a flag?

**Comment by Mic92** [comment]
Sounds more like a cancellation bug again. How reproducible is that?

**Comment by Mic92** [comment]
As you can see here the normal control flow should always return 1: https://github.com/Mic92/nix-fast-build/blob/d0a3fe039c5ce3140b96473cab44b7a8bd0d34f5/nix_fast_build/__init__.py#L802
But maybe there is some bug in the code due to asyncio.

**Comment by Mic92** [comment]
I had bugs like that in early versions of nix-fast-build, so please make sure you have not used those.

**Comment by colemickens** [comment]
Here's a run showing this behavior: https://github.com/colemickens/nixcfg/actions/runs/6513223323

And the commit it ran on: https://github.com/colemickens/nixcfg/commit/b1c51501db88e4128292176c041c05c3046e599f

And the version of nix-fast-build [from that tree's lock](https://github.com/colemickens/nixcfg/blob/b1c51501db88e4128292176c041c05c3046e599f/flake.lock#L873-L880) is [mic92/nix-fast-build@d0a3fe039](https://github.com/Mic92/nix-fast-build/commit/d0a3fe039c5ce3140b96473cab44b7a8bd0d34f5)

which is current tip of tree for `nix-fast-build`.

So I feel mostly confident that it's still an issue.

**Comment by colemickens** [comment]
another instance: https://github.com/colemickens/nixcfg/actions/runs/6558427567/job/17811973473

a networkd option just became required and my CI missed it, even though it shows in logs.

**Comment by Mic92** [comment]
Does this also happen reliable if you restart the build? Can you trigger this locally?

**Comment by Mic92** [comment]
Ah. This only happens for eval errors, not build errors. Right?

**Comment by colemickens** [comment]
ah, sorry for the bad title, yes, I've only seen this for eval errors.

**Comment by Mic92** [comment]
I extended the testsuite to explicitly check for eval errors: https://github.com/Mic92/nix-fast-build/blob/e76d62f7d0e67c93b41f16f2a72afc862cfa1a88/.github/workflows/tests.yml#L29

**Comment by Mic92** [comment]
I can not reproduce this issue here:

```
/tmp/dreamy-varahamihira-HGPvob/nixcfg main
% git checkout b1c51501db88e4128292176c041c05c3046e599f
HEAD is now at b1c51501 fixup CRLF EOL nonsense
direnv: unloading

/tmp/dreamy-varahamihira-HGPvob/nixcfg main~130
% nix run /home/joerg/git/nix-fast-build --
INFO:nix_fast_build:run nix-eval-jobs --gc-roots-dir /tmp/tmpti9via7z --force-recurse --max-memory-size 4096 --workers 8 --flake '.#checks'
warning: unknown setting 'allowed-users'
warning: unknown setting 'trusted-users'
⏱︎ 1serror (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error (ignored): error: SQLite database '/home/joerg/.cache/nix/eval-cache-v5/268444f05fed946c580919a1281b7edab2ea6f4123e722d1f8bf1d40e203a3b3.sqlite' is busy
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
error: worker error: error: flake 'git+file:///tmp/dreamy-varahamihira-HGPvob/nixcfg' does not provide attribute 'checks'
ERROR:nix_fast_build:nix-eval-jobs exited with 1

noglob nix run /home/joerg/git/nix-fast-build --  4.00s user 1.53s system 66% cpu 8.314 total
```

**Comment by colemickens** [comment]
Can you try a run where `nix-eval-jobs` successfully evals some checks but not others? I wonder if that's what's causing my issue. Looking at the logs for the cases I posted above, I'm still mostly convinced there's some sort of bug somewhere. I'm definitely not ignoring errors from nix-fast-build and the CI was still showing green.

**Comment by Mic92** [comment]
Possible. I had concurrency issues in the past with asyncio that only showed up in certain environments.

**Comment by colemickens** [comment]
I just caught my CI doing this on another command (nix-update, heh). And yeah, it's not a bug in `nix-fast-build`. Context: https://github.com/nushell/nushell/issues/10856
