### ISSUE TITLE
call nix-build with --out-link to preserve result links

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-fast-build#35]
Hi,

I'm using cachix, and I've been blindly doing `ls result* | cachix push {cache}` and just now realizing that the way `nix-fast-build` works seems to be clobbering result as it goes.

So, I've been getting lucky that my slowest host to build often includes most things.

It would be nice if I can easily access the things built by `nix-fast-build` after the fact. Maybe if it took the attr name from the eval and then passed it as `--out-link` to nix-build ?

**Comment by colemickens** [comment]
I am trying to add this, but I don't know if I'm ever going to get along with python. It spits out a ton of exceptions, none of which were helpful, and then said there were 33 more. when testing on a single output attribute. :shrug:

**Comment by colemickens** [comment]
I don't know why `nix-eval-jobs` is outputting a blank `attr` for this eval... but that's the issue.

**Comment by colemickens** [comment]
from a quick look, it seems like `attr` is populated when it's building as part of checks, instead of a specific output ref passed to `nix-eval-jobs`. I guess a bug on `nix-eval-jobs`?

**Comment by colemickens** [comment]
okay, I have something working that outputs result links:

```
result-alacritty-unstable-2023-10-25
result-cole-nixcfg-dev
result-emmc_appsboot-test-signed.mbn
result-git-repo-manager-unstable-2023-08-28
result-mobile-nixos_openstick_boot.img
result-nixos-23.11.20231026.bfdb008-x86_64-linux.iso
result-nixos-system-installer-23.11.20231026.bfdb008
result-nixos-system-openstick-23.11.20231026.bfdb008
result-nixos-system-raisin-23.11.20231026.bfdb008
result-nixos-system-slynux-23.11.20231026.bfdb008
result-nixos-system-zeph-23.11.20231026.bfdb008
result-nushell-unstable-2023-10-25
result-rio-unstable-2023-10-26
result-shell-ci
result-uutils
result-wezterm-unstable-2023-10-17
```

but preferably the `attr` value would be reliable, as I like those names better:

```
  building x86_64-linux.package-x86_64-linux.alacritty
  building x86_64-linux.devShell-x86_64-linux.uutils
  building x86_64-linux.package-x86_64-linux.nushell
  building x86_64-linux.package-x86_64-linux.git-repo-manager
  building x86_64-linux.package-x86_64-linux.rio
  building x86_64-linux.package-x86_64-linux.wezterm
  building x86_64-linux.extra-aarch64-linux.openstick-abootimg
  building x86_64-linux.extra-aarch64-linux.openstick-bootimg
  building x86_64-linux.devShell-x86_64-linux.dev
  building x86_64-linux.devShell-x86_64-linux.ci
  building x86_64-linux.devShell-x86_64-linux.default
  building x86_64-linux.toplevels-installer
  building x86_64-linux.extra-x86_64-linux.installer
  building x86_64-linux.toplevels-openstick
  building x86_64-linux.toplevels-slynux
  building x86_64-linux.toplevels-raisin
  building x86_64-linux.toplevels-zeph
```

Any tips would be appreciated, even if it's "file a bug on nix-eval-jobs".

**Comment by colemickens** [comment]
An alternative approach here could be to have the ability to run a "post-build command", so that the out-link would get piped into the command of my choice. The goal would be able to run `cachix push` on the outPaths, and have that done remotely if the build is running remotely.

**Comment by Mic92** [comment]
Cachix/attic is probably something that should be supported natively like nix copy.
