### ISSUE TITLE
error building with ca-derivations

### ISSUE THREAD

**Issue by apt-install-coffee** [Mic92/nix-fast-build#70]
Attempting to build packages with contentAddressedByDefault = true causes what looks like a package lookup error

nix-fast-build -f ".#nixosConfigurations.{{target}}.config.system.build.vm" --eval-workers {{num_cpus()}} --skip-cached

``` error:
              … while evaluating an output path of a derivation
                at /nix/store/6gl54qrif8gpqn00c8v2zf6rlqv5cwkr-source/lib/customisation.nix:352:13:
                 351|             drvPath = assert condition; drv.${outputName}.drvPath;
                 352|             outPath = assert condition; drv.${outputName}.outPath;
                    |             ^
                 353|           } //

              error: path '/0l3nhbpf8k5pp8f35zgjcqhj7i0nb6vl9i6wxkh7dpijc396j8rw' is not in the Nix store```

running
nix build .#nixosConfigurations.{{target}}.config.system.build.vm
results in a successful build.

**Comment by Mic92** [comment]
Ok. But is this than not a general issue with nix than or does it only break in nix-fast-build specifically?

**Comment by Mic92** [comment]
Mhm. I have to actually check if you can pass a single derivation this way. There is actually not much point in using nix-fast-build for a single derivation. At this point you could just use `nix build` directly.

**Comment by Mic92** [comment]
Cool. I didn't think this can actually work: 

````
./result/bin/nix-fast-build --flake $HOME/.homesick/repos/dotfiles#nixosConfigurations.turingmachine.config.system.build.vm
```

**Comment by apt-install-coffee** [comment]
I'm only passing a single derivation currently to minimize code surface area when debugging, and my development builds do just run 'nix build'.

A full release build would include multiple derivations.

**Comment by apt-install-coffee** [comment]
I should also note that running the same nix-fast-build command with a {{target}} derivation that does not use content-address derivations does succeed.

**Comment by Mic92** [comment]
Is the issue maybe that nix-eval-jobs work with ca-derivations?

**Comment by apt-install-coffee** [comment]
Ah, you're correct, the issue seems to be in nix-eval-jobs

**Comment by Mic92** [comment]
Well. I am also the maintainer of that, so feel free to open an issue there.
I haven't looked into ca-derivation yet, but it would be an interesting extension for buildbot-nix because it allows to run impure derivations.
