### ISSUE TITLE
Ram usage building .#nixosConfigurations

### ISSUE THREAD

**Issue by covert8** [Mic92/nix-fast-build#73]
Hi love the project, thinking of doing some work on it and I would like some feedback before starting.

By default the `.#checks` get build and I added my `.#nixosConfigurations` like so:

`checks.x86_64-linux = lib.mapAttrs' (name: config: lib.nameValuePair "${name}" config.config.system.build.toplevel) self.nixosConfigurations;`

However, this resulted in additional downloads when doing a plain `nix flake check` and prolonging the check duration; so I found this sub optimal as I like to check on a tmpfs.

To avoid the default `.#checks` I passed `-f .#nixosConfigurations` but that results in an OOM on the evaluator (>64GB;no tmpfs ; 5 hosts) and not completing any derivation in a timely fashion. I ended with this:
```
hosts=$(nix flake show --json | jq -r '.nixosConfigurations | keys | .[] | select(. != "C60006") |  ".#nixosConfigurations." + . + ".config.system.build.toplevel"')
while read -r host; do
    nix-fast-build -f "$host" --no-nom -j 1 --eval-workers 1 --skip-cached
done <<<$hosts
```
My questions:
* Is there a way to simplify the while loop? 
* Do you think it is feasible to remove already uploaded derivations (when using the cachix daemon) to make more ram available during a build?
* Would you accept a pr supporting the `attic` client?

**Comment by Mic92** [comment]
I would expose nixos hosts in checks actually:

https://github.com/Mic92/dotfiles/blob/f44bac5dd6970ed3fbb4feb906917331ec3c2be5/flake.nix#L191

Than you don't need a loop at all.

**Comment by Mic92** [comment]
And for RAM usage, you can always change the number of concurrent evaluations:

https://github.com/nix-community/nix-eval-jobs?tab=readme-ov-file#nix-eval-jobs-consumes-too-much-memory--is-too-slow

**Comment by covert8** [comment]
Thanks for all the help and good work!
