### ISSUE TITLE
Feature request: Machine-readable build manifest

### ISSUE THREAD

**Issue by ryanccn** [Mic92/nix-fast-build#78]
It would be great if `nix-fast-build` could optionally write to a manifest reporting the outcome of builds, containing information such as the built attribute, success/failure/failure type, path in the Nix store, etc., in a machine-readable format such as JSON.

This would be very helpful for situations involving automation and/or status reporting, such as CI/CD.

**Comment by Mic92** [comment]
Is there some standard format CIs already understand out of the box?

**Comment by ryanccn** [comment]
> Is there some standard format CIs already understand out of the box?

Not that I'm aware of (I primarily use GitHub Actions); in any case IMHO it would be better if `nix-fast-build` had its own simple format that users can then process with tools like `jq` however they want.

**Comment by Mic92** [comment]
Implemented in https://github.com/Mic92/nix-fast-build/pull/74
