### ISSUE TITLE
doc feat: document how --remote works

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-fast-build#8]
Hi,

It's looking like this could drastically reduce my current "wrapper" script of sorts, but one of the things my wrapper does is do local evaluations, push the derivations to a remote, and then SSHs and does the build+cachix call on the remote machine.

This avoids the issue (that I think is still an issue?) of Nix's behavior of building/pulling derivations one at a time to/from a remote.

Does `nix-fast-build` do this too? Or is it using the built-in remote builder functionality of nix?

**Comment by Mic92** [comment]
Please check if https://github.com/Mic92/nix-fast-build/commit/acd8ff4244aff11b997fabb38b82c161bb25a13b explains it better.

**Comment by colemickens** [comment]
Crystal clear. Thanks @Mic92 !
